version: "2.4"
services:
  API:
    image: datascientest/fastapi:1.0.0
    ports:
      - "8000:8000"
    healthcheck:
      test: exit 0
      interval: 5s
      timeout: 5s
      retries: 1
      start_period: 5s
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2 

  authentication:
    build: ./authentication
    environment:
      - LOG=1
      - api_address=10.5.0.2
      - api_port=8000
    depends_on:
      API:
        condition: service_healthy
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3  

  authorization:
    build: ./authorization
    environment:
      - LOG=1
      - api_address=10.5.0.2
      - api_port=8000
    depends_on:
      API:
        condition: service_healthy
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

  content:
    build: ./content
    environment:
      - LOG=1
      - api_address=10.5.0.2
      - api_port=8000
    depends_on:
      API:
        condition: service_healthy
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5  

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1                   
